# Generated by Django 3.2.4 on 2021-08-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_Name', models.CharField(max_length=200)),
                ('Seller_Address', models.CharField(max_length=200)),
                ('Seller_Number', models.CharField(max_length=12)),
                ('Buyer_Address', models.CharField(max_length=200)),
                ('Buyer_Number', models.CharField(max_length=12)),
                ('Item_Name', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('Item_Quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Item_Price', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
