# Generated by Django 3.2.4 on 2021-08-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210818_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_Name', models.CharField(max_length=200)),
                ('Seller_Address', models.CharField(max_length=200)),
                ('Seller_Number', models.CharField(max_length=122)),
                ('Buyer_Address', models.CharField(max_length=200)),
                ('Buyer_Number', models.CharField(max_length=122)),
                ('Item', models.CharField(max_length=120)),
                ('Quantity', models.PositiveIntegerField()),
                ('Price', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Invoice1',
        ),
    ]
